[font]
size = 14.0

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

# Mirage theme from Ghostty
# in /usr/share/ghostty/themes/Mirage if you have Ghostty installed
[colors.primary]
background = '#1b2738'
foreground = '#a6b2c0'

[colors.cursor]
cursor = '#ddb3ff'
text = '#ffffff'

# the rest of the colors are the TokyoNight theme
# from https://github.com/folke/tokyonight.nvim/blob/main/extras/alacritty/tokyonight_moon.toml
# Normal colors
[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
[colors.bright]
black = '#444a73'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#c8d3f5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'
